spring:
  application:
    name: shutter-box-v2
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

aws:
  region: ${AWS_REGION:eu-central-1}  # use env var or fallback to eu-west-1
  s3:
    bucket: ${BUCKET_NAME:shutter-box-v2-images}  # use env var or fallback

logging:
  level:
    org: WARN
