spring:
  application:
    name: shutter-box-v2
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
aws:
  region: eu-west-1  # fallback to eu-west-1 if not set
  s3:
    bucket: shutter-box-v2-images
